### ISSUE TITLE
Login language brings attention to physical appearance

### ISSUE THREAD

**Issue by isaacs** [npm/newww#1046]
Pretty valid objection, I think: https://twitter.com/johnonolan/status/611604706562035712

That "you look lovely today, btw" language was originally intended to be a light-hearted place-holder, but it sort of stuck and was never re-thought.

It's worth re-thinking.  Physical appearance isn't really relevant to the npm experience.  For every person whose confidence is slightly boosted in some way, it probably makes someone else a bit uncomfortable.

Since the persona of npm is an empathic robot filled with an abundance of platonic love for all meatbags and wishes for their success and happiness, bringing physical appearance into the equation makes it a bit weird.

**Comment by othiym23** [comment]
:+1: It was a nice little filip in the design when we relaunched the site, but if it makes people uncomfortable (and that's not the first time I've seen that sentiment expressed), it's for the best to replace it with something more anodyne / less relevant to appearance.

**Comment by JohnONolan** [comment]
> Since the persona of npm is an empathic robot filled with an abundance of platonic love for all meatbags and wishes for their success and happiness, bringing physical appearance into the equation makes it a bit weird.

This.

It is absolutely possible to have fun and light-hearted UX. But this language is so creepy. Why does a machine "love me"? Why does it want me to let me know I look good today? Ut feels like a cross between Big Brother and sexual predator.

Humans loving other humans :+1: 
Computers loving code :+1:
npm loving its community, or a group, eg "developers" or "geeks" :+1: 
npm loving a concept, like productivity or asynchronicity  :+1: 

Those are all super basic things which are inclusive, non-personal, and still convey a similar message.

Personally - if the point of these messages is unexpected and delightful UX (and it seems like it is) I would do something more interesting and useful. Have the footer be a rotating array of strings like Slack's login message, which range from quick tips (like keyboard shortcuts), to interesting facts in the style of uberfacts.

Eg. I only found out the other day that I can just write "npm i" instead of install. That's actually really cool, and I only found it because one of Isaac's old blog posts popped up in a search result.

Just my 2c. Thanks for addressing this

**Comment by isaacs** [comment]
> Eg. I only found out the other day that I can just write "npm i" instead of install.

This is a GREAT idea.  I'll ask around the team here and maybe try to solicit some ideas for a few 5-word-or-less "did you know?" type suggestions.  It should probably be a separate module, kinda like how we do "npm" expansions.

**Comment by isaacs** [comment]
First pass at this: https://github.com/npm/npm-tips

**Comment by isaacs** [comment]
Will be addressed by https://github.com/npm/newww/issues/1047.  Closing this now, since we've come to a workable solution.

Thanks again for raising this issue, @JohnONolan.
