### ISSUE TITLE
Pull marketing windows into website UI according to ranked user states

### ISSUE THREAD

**Issue by seldo** [npm/newww#1670]
Here is the 3 named locations

![d1502e98-817c-11e5-97fe-6b4f1940aeeb](https://cloud.githubusercontent.com/assets/185893/11857747/09cdbf8c-a410-11e5-8971-6ac287034e96.png)

how tall each one is
- top: 150px
- middle: 26 px
- side: variable

Dismissibility:
- top & middle - yes dismissible
- side: ~should vary. some content should not be dismissible, some not.~ not dismissible

Position: 
- in the case of the package page, where it appears relative to everything else in the sidebar, it should appear as the top element, 40px above installation instructions, 10px to the left of other sidebar elements. (eventually will want to optimizely test other positions.)

Tags are chosen according to [this spreadsheet](https://docs.google.com/a/npmjs.com/spreadsheets/d/1kRnv3NTuLVkFqC6RiIdCXFw5sbIPbuY44xXIagjBifw/edit?usp=sharing)

**Comment by seldo** [comment]
The very simple API for WP is "documented" here https://github.com/npm/marketing-integration/issues/29#issuecomment-155228344 but is basically like this:

`http://wordpress.internal.npmjs.com/wp-json/npm/v1/promotions?user_vars[]=isSignedIn`

`user-vars` is an array because you can send multiple tags. It is an `OR` field, so if you send multiple tags it will pick something that matches any of those tags, and if multiple things match the tags the behavior is (as far as I can determine) undefined.

**Comment by seldo** [comment]
Size and positions of windows to be integrated are now spec'ed here: https://github.com/npm/issue-tracker/issues/387#issuecomment-166454825

**Comment by seldo** [comment]
The order in which to pick a single tag to send is here: https://github.com/npm/issue-tracker/issues/390#issuecomment-166477516

I declare this ticket unblocked.

**Comment by aredridel** [comment]
Position / size / dismissibility discussion was at  https://github.com/npm/issue-tracker/issues/387.

Tag choice discussion at https://github.com/npm/issue-tracker/issues/390.

**Comment by cowperthwait** [comment]
The package-page sidebar window should render at the very top of the left navigation area ([screenshot of current spike system](http://dl.dropbox.com/u/73197268/Screenshots/0_tc.png)), but in the current staging environment, it is rendering below a package’s “npm install…” instructions ([screenshot of appearance in staging](http://dl.dropbox.com/u/73197268/Screenshots/j5lb.png)).

Since there are other visual discrepancies between these two pages, I don’t know whether my issue relates to engineering of the marketing window itself, or whatever other work, documented elsewhere, has changed the design on the production site.

**Comment by aredridel** [comment]
Yeah, the integration of the spike mucked with that a bit, and I haven't finished styling and positioning, so that works. I'll do that and integrate it.

**Comment by cowperthwait** [comment]
thx

**Comment by aredridel** [comment]
Spec clarified with regard to positioning relative to other sidebar elements, gap between them etc.
