### ISSUE TITLE
relax CSP to disable `unsafe-eval` on marketing pages

### ISSUE THREAD

**Issue by cowperthwait** [npm/newww#1768]
per a Slack conversation w/ @aredridel: marketing would like to embed a SurveyMonkey script on a WordPress-rendered page, but because the script includes eval shenanigans, this requires relaxing `unsafe-eval`.

This applies only to pages under the `/npm/*` namespace, so same domain/origin as other pages, but not on pages with any user generated content.

- [x] Aria to request feedback from Adam Baldwin
- [ ] CSP update itself

**Comment by stubbornella** [comment]
@evilpacket - how does this sit with you?

**Comment by evilpacket** [comment]
@stubbornella doing a bit of research then will have thoughts.

**Comment by evilpacket** [comment]
Typically there is no good reason to be doing some sort of eval shenanigans. They might have a good reason, but it would seem prudent to talk with them and see if they have options for getting around this, maybe they are working on a version that is more friendly with csp? (it's possible they already told you no which lead us to this point).

It would also seem like a good idea to audit this particular use of eval to see if any vulnerability exists in their implementation ultimately passing that risk onto the site once unsafe-eval is allowed.

Do you have a link to the particular script you want to include?

**Comment by aredridel** [comment]
It's https://widget.surveymonkey.com/collect/website/js/j1bKVf9t8MFlqbfiTb7_2FoUj8x9UlC3fmijxjfKOCpNVm1959rdk4l6Pt35BM1cBx.js -- particularly, it injects inline scripts as its eval() equivalent.

**Comment by aredridel** [comment]
It's one of those unbelievably obfuscated loaders :/

**Comment by evilpacket** [comment]
Because the application and privileged actions do not run with privilege separation I don't think it's a good idea and makes me quite nervous to disable unsafe-inline.

This is a good read on how dropbox tackled the problem of third party integration to reduce the risk https://blogs.dropbox.com/tech/2015/09/csp-third-party-integrations-and-privilege-separation/

**Comment by aredridel** [comment]
Yeah. iframe sandboxing is a good thing, but it's expensive.

**Comment by evilpacket** [comment]
That's about all I have. It's the balance of, do we trust [third party] to not get compromised and serve up content that compromises our users or be creating a vulnerability with their obfuscated and un-auditable code. Maybe you can host that script instead of loading it straight from them to help reduce that. 

I don't know if I would want to extend that privileged to a third party given the importance. It's a tough balance. I would if anything ask them to consider making a csp friendly version of their script if you continue to plan to use their product. I don't think that's an unacceptable request.

**Comment by aredridel** [comment]
@cowperthwait How is our relationship with Surveymonkey etc? Are there pages we can brand npm that are off-domain so they're not sharing an origin with www.npmjs.com? Are iframe integrations workable?

**Comment by cowperthwait** [comment]
> How is our relationship with Surveymonkey etc?

We do not represent a large customer of SurveyMonkey — we’re on their lowest subscription tier — nor am I personally close to anyone high-enough up at the company that I’d be persuasive in asking them to provide a bespoke CSP-friendly version of their script.


> Are there pages we can brand npm that are off-domain so they're not sharing an origin with www.npmjs.com?

For this specific survey: @ashleygwilliams and I can spin up a landing page elsewhere, e.g., GitHub pages.

Speaking generally: third-party scripts that are widely used by marketers, but do not meet our (rigorous!) security requirements, will be a recurring issue for our team, and hosting all of this content off-domain is sub-optimal
* branding coherence
* a significant motivation for moving marketing’s work to its own CMS was to furnish a way for marketing to self-sufficiently create and host content without affecting `newww` content and workflow; requiring that interactive content live off-CMS diminishes its value

**Comment by cowperthwait** [comment]
> Are iframe integrations workable?

If I’m provided with the necessary engineering resources to:
- [ ] spin up a system on which content like this script can be posted and executed
- [ ] iframe embed content from this system within our standard `newww`-rendered chrome

… then it would be a less-than-ideal but workable implementation for me.

Disadvantages:
* can’t be certain that all third-party tools won’t try to framebust, though in the case of Survey Monkey’s, I can’t imagine why they would
* implications for cross-domain analytics tracking must be carefully understood and accommodated

**Comment by isaacs** [comment]
Using iframes is not a feasible solution.

If we do this on a different TLD, it is also some engineering lift to put the login widget on the upper-right corner for user experience coherence.

@aredridel or @evilpacket, is it possible to relax unsafe-eval CSP for a specific domain?  We could then allow SurveyMonkey's (or whoever's) evals to run, without allowing whatever eval might be injected in there if those systems are compromised.

I'd like to get @seldo's pov on this, since we're setting technical policy for the company, and that's part of what a CTO does :)

**Comment by evilpacket** [comment]
@izs I do not believe so as it's a keyword of script-src but the policy could be lowered only on certain marketing pages, which does Lilith exposure.

**Comment by evilpacket** [comment]
If you can host the JS yourself that's the best. Then we only have to worry about vulns in that script not compromise from that domain (or other third party included scripts)

**Comment by seldo** [comment]
So, having talked to @cowperthwait in-air, the use-case for this survey is: users will get an email that contains a link to the survey, which will render on a page by itself. That page is npm-branded but is not tied to the look and feel of the site. Users are not expected to get to this page by browsing the main npmjs.com, and they can be easily redirected to npmjs.com once they are done.

Therefore, it is totally practical to host this survey on a totally separate domain, and it will not impact the user experience, because the link in the email will already be obfuscated by click-tracking, so they won't be able to tell what domain they're going to in the first place.

Solution: pick one of the following available npm domains that we already own:

npm.technology
npm.tips
npm.rocks
npm.computer
npm.mn
npm.so
npm.today
npm.red
npm.xyz
npmcamp.com
npm.camp

Throw up a page that consists of nothing but this widget, and we're done.

@cowperthwait's larger point, and it is a good one, is that most marketing tools require the ability to do things that worry us security-wise, and that's true, but allowing unsafe-eval *and* unsafe-inline only for SurveyMonkey in a situation where the user experience is not impacted is a bad risk-reward ratio. When other tools come along we will make this call again. People like Optimizely are not doing things nearly as egregiously unsafely as SurveyMonkey.

**Comment by cowperthwait** [comment]
See: [http://wombat.npmjs.com/newsurvey](http://wombat.npmjs.com/newsurvey). With a little finessing of iframe style rules, I’m confident this will suffice.

**Comment by aredridel** [comment]
Oh that looks delightful!

**Comment by aredridel** [comment]
As a follow-up to this: optimizely looks to have a CSP-friendly feature subset we can use, which will help immensely.
