### ISSUE TITLE
Security issue on misleading package name uglifyjs

### ISSUE THREAD

**Issue by fibo** [npm/newww#1917]
Please read this issue https://github.com/mishoo/UglifyJS2/issues/936

we tryed to contact you following the policy provided but we got no answer.

Many people is installing a misleading version of uglify js. Can you solve it, please?

**Comment by isiahmeadows** [comment]
@fibo I agree it's misleading, but I would like to note two things:

1. @mishoo should be the one contacting npm - he's the package owner. I do feel the "contact the author" part has been tried, though.
2. I've inspected the package, and it appears to be fully innocent, as in no malware. I am no security professional, though.

**Comment by mishoo** [comment]
I agree that should be removed, but it seems there are projects depending on it.  Any case, not sure what I should personally do about it…

**Comment by isiahmeadows** [comment]
@mishoo It's a known problem. People make typos and forget about them.

The problem with the package in question is that it hasn't been updated in over a year. Since then, it's only been minor, almost patch-level changes as far as I've seen, mostly in the area of stability. I suspect it'll probably end up getting the same treatment as [coffeescript](https://www.npmjs.com/package/coffeescript), which warns you on its preinstall hook that it's a misspelling of [coffee-script](https://www.npmjs.com/package/coffee-script), and those maintainers will know within a week when people complain to them that the package fails to install, if they're even partially paying attention. Literally adding a dash to fix it will break nothing, because of npm's versioning scheme, if they're using it properly (and if they aren't, it's not your problem, and like I implied earlier, even a `*` version shouldn't cause too many problems).

Besides, almost 10 million downloads in the past month for the real package vs ~30 thousand for the one in question, I don't think it's going to have that much of an impact.

**Comment by fibo** [comment]
But why you do not try to contact him or do something instead of writing a comment here trying to explain me something I do not agree, you could write an email to him.

If a user spend time like me, trying to notify a misleading behaviour, try to listen to him instead of bla bla bla.

I wrote him and I got no answer, he could be a bot, he could be whatever, who knows.

Just a typo like that should make you think: **less quality** in npm packages and ecosystem.

The fact that users give you feedback and you don't want understand, even more in these days when you got so much issues, is not good for npm.

Listen more to active users, enhance the ecosystem with some karma points or something like stack overflow that let users improve the system.

> 30000 downloads

it is huge! And mr nobody, who do not answer emails could publish a malicious package in the future.

But most of all, listen to your users. I tryed to do something but if I find a wall, next time I will leave you in the ignorance where you are swimming

**Comment by kzc** [comment]
@fibo Your efforts to resolve this issue are appreciated.

At this point I think that only @mishoo and @isaacs can resolve this `uglifyjs` package name impasse.
