### ISSUE TITLE
Package Page Layout

### ISSUE THREAD

**Issue by mattdesl** [npm/newww#414]
Awesome work with the new site, looks crisp!

I'm wondering whether the new package page lays out information in the most efficient way... Just opening this up for discussion.

GitHub does a good job at giving us author, number of commits, code, and open issues/PRs upfront. This makes it easy to make a rough guess about the quality of package, and how safe it is to depend on. 

IMHO info like this is the most important thing in a package page and should be delivered first to the user. For browsers under 1170px wide (i.e. every time I view a package), this is buried very far down under the readme, and even for wide screens you often need to scroll down just to see a list of maintainers / dependents / dependencies (which are all more important than keywords for me). 

Thoughts?

For reference:

![img](http://i.imgur.com/iuIXT7v.png)

**Comment by Undeterminant** [comment]
The main reason for designing a responsive layout is to respond to all resolutions in a reasonable range, not to simply have a mobile website and a desktop website in the same layout. If you're going to do that, you might as well design two separate websites, like Facebook, Twitter, and GitHub all seem to do.

I use a tiling window manager, and to get the most out of a 1920x1080 resolution monitor, I split my browser in half with 65% of the screen dedicated to one window and 45% of the screen dedicated to the rest. That brings it down to 1248 pixels on the large window, but including the scrollbar and [Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab) brings the value below 1000px, which still isn't close to the desktop layout.

I would be fine with such a large requirement if the desktop layout actually needed it, but the difference between the two layouts is literally between [this](http://i.imgur.com/LD5HSbt.png) and [this](http://i.imgur.com/R5F7oCm.png). To me, it seems totally unreasonable to keep the threshold so high, especially with all of that unused space.

A discussion of how many users have certain screen sizes is totally irrelevant IMO because the window can be resized. A user with a 1280px-wide screen can cut their screen in half for around 640px, which is another resolution in which the website wouldn't look very good.

It makes sense that the size of the desktop version would be cut down to the bare minimum width to keep the layout stable, and then the phone version would be cut to a reasonable maximum size, then some layout would be worked out for the middle if those two numbers don't reach each other.

**Comment by zeke** [comment]
Thanks for the added context, @Undeterminant. I agree that the site should look good at any resolution. :)

**Comment by mattdesl** [comment]
The current layout also leads to some huge images, like in [glsl-film-grain](https://www.npmjs.com/package/glsl-film-grain). 

I think the solutions here are to use a hard limit (like GitHub) or try to distinguish between mobile/desktop UX more reliably than browser width.

**Comment by zeke** [comment]
Some improvements to layout stuff rolled out silently along with private modules last week:

- The threshold for mobile layout is now around `760px` instead of `1170px`, so the pushed-down stats and the giant gravatar issue is much less prevalent. 
- Packages with long readmes are still not great on mobile. I opened a separate issue for that: https://github.com/npm/newww/issues/905
- `npm install` is shortened to `npm i` for long package names
- I'm working on a refactor of the github stats code, so we can display more interesting github-related stats like issue, PR, and contributor counts on package pages without cooking more spaghetti code. See https://github.com/npm/newww/pull/824

I'm gonna close this, but feel free to open more granular issues related to anything I've missed.
