### ISSUE TITLE
css usage license

### ISSUE THREAD

**Issue by NikhilKalige** [npm/newww#607]
I made use of the stylesheets from this repo inorder to create a website...http://atom.shortcircuits.io and the source is at https://github.com/NikhilKalige/atom-website. I have added the license from this repo @ https://github.com/NikhilKalige/atom-website/blob/master/LICENSE.

Can you please let me know if am violating anything

**Comment by seldo** [comment]
Hi @NikhilKalige! From a copyright perspective your are entirely in the clear, since the code is under an ISC license. However, from a branding perspective and to minimize confusion, we'd prefer if you made the site a different color or in some other way a little more visually distinguishable from our own :-)

**Comment by NikhilKalige** [comment]
@seldo I think i understand your concerns... I will make the necessary changes.. But i don't think anybody will be visiting mine :)
